### ISSUE TITLE
create summary network - missing singletons

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#81] opened 2017-03-20 15:03 UTC
When creating a summary network through auto-annotate only the clusters are summarized.  The singletons do not get transferred to the new network.

**Comment by risserlin** [comment] 2017-03-20 15:23
work around  - manually add cluster numbers to each of the singletons and re-create annotation, then create summary network.

**Comment by mikekucera** [comment] 2017-07-17 15:32
Duplicate of #65

**Comment by mikekucera** [comment] 2017-07-17 15:32
Duplicate of #65

**Closed as completed by mikekucera** 2017-07-17 15:32 UTC
Labels: bug, duplicate
