### ISSUE TITLE
Modify multiple annotations together

### ISSUE THREAD

**Issue by dhollan9** [BaderLab/AutoAnnotateApp#48] opened 2016-03-31 21:15 UTC
Suggested enhancement: It would be convenient if you could modify the shape and color of multiple annotations at once. As it stands, you can change the opacity, the border width, and toggle between rectangle and ellipse shaped annotations. You have to change each annotation one by one if you want to use a different shape (e.g. rounded rectangle) or color.

**Comment by mikekucera** [comment] 2022-11-02 19:29
Duplicate of https://github.com/BaderLab/AutoAnnotateApp/issues/39

**Closed as completed by mikekucera** 2022-11-02 19:29 UTC
Labels: enhancement
