### ISSUE TITLE
clustering algorithm used for auto annotate doesn't ignore hidden nodes

### ISSUE THREAD

**Issue by risserlin** [BaderLab/AutoAnnotateApp#9] opened 2016-01-14 18:48 UTC
bug is obviously with the clustering program but would be good if auto annotate selected all visible nodes and ran clustermaker with "selected nodes only" option.

**Comment by mikekucera** [comment] 2017-12-11 16:43
Duplicate of #29

**Closed as completed by mikekucera** 2017-12-11 16:43 UTC
Labels: enhancement
