### ISSUE TITLE
autoannotation of an EM with post-analysis

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/AutoAnnotateApp#90] opened 2017-06-02 19:54 UTC
I'm annotating a subnetwork containing postanalysis nodes and edges. I don't need the post-analysis nodes to be included in the autoannotation. Is there a way to unselect nodes we don't want to be part of the annotation? 
![screen shot 2017-06-02 at 3 53 06 pm](https://cloud.githubusercontent.com/assets/7570379/26742418/997ecc58-47ab-11e7-9709-f221d8281f09.png)

**Comment by mikekucera** [comment] 2017-06-02 20:39
Not at the moment. This is a feature that will be added in 1.2. For now you have to select the clusters in the panel and delete them.

**Comment by mikekucera** [comment] 2017-07-12 19:11
Duplicate of #88

**Closed as completed by mikekucera** 2017-07-12 19:11 UTC
Labels: duplicate, enhancement
