### ISSUE TITLE
Not able to use "User-defined clusters"

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/AutoAnnotateApp#139] opened 2018-12-20 16:09 UTC
As I had a cluster that was too large with AutoAnnotate, I tried to first run ClusterMaker MCL with some specific parameters and run AutoAnnotate using 'User-defined clusters'. However , I'm not able to see and select the MCL cluster column in the box. This column is present in my node table.
please see screenshot.
![screen shot 2018-12-20 at 11 04 34 am](https://user-images.githubusercontent.com/7570379/50296114-b0635600-0447-11e9-9e76-eecc0ff011d1.png)

**Comment by mikekucera** [comment] 2021-03-10 18:20
Duplicate of #160

**Closed as completed by mikekucera** 2021-03-10 18:20 UTC
