### ISSUE TITLE
meta-edges created by AutoAnnotate question

### ISSUE THREAD

**Issue by ctekellogg** [BaderLab/AutoAnnotateApp#112] opened 2017-11-03 20:33 UTC
Hi, I am trying to use AutoAnnotate to group nodes (which represent microbial operational taxonomic units - OTUs) by taxonomy.  My network shows both positive and negative correlations between nodes, but when collapse the groups created by AutoAnnotate, these edges are grouped into one meta-edge and info regarding the number of positive correlations and negative correlations between meta-nodes is lost. Is it possible to preserve this information so that I can show both the positive and negative correlations between meta-nodes and also scale the meta-edges by number of pos or neg correlations?  This would be amazing!

**Comment by mikekucera** [comment] 2017-11-06 18:32
Attribute aggregation for meta-edges is not yet supported by Cytoscape, its currently only supported for nodes. I could add this as an enhancement to the "create summary network" feature in AutoAnnotate. Would that work for you?

**Comment by risserlin** [comment] 2017-11-06 18:46
For your use case thematic map might help (http://apps.cytoscape.org/apps/thematicmap).  You can use the the cluster number as the attribute for the thematic map and there are different ways to summarize the edges.

**Comment by ctekellogg** [comment] 2017-11-07 07:19
Thank you for getting back to me about this. Yes, I think having a feature to summarize edges in addition to nodes would be helpful as a means for people to summarize their networks. I think I may have found a work around for the time being (a custom script from someone that summarizes my network and then i load that summary into cytoscape, instead of the 'raw' network), but this could be a useful function overall.  Especially being able to distinguish this positive meta-edges from negative meta-edges.

**Comment by mikekucera** [comment] 2021-04-28 15:20
Duplicate of #165

**Closed as completed by mikekucera** 2021-04-28 15:20 UTC
Labels: duplicate, enhancement
