### ISSUE TITLE
enhancement style: add a slide bar to reduce ellipse size?

### ISSUE THREAD

**Issue by veroniquevoisin** [BaderLab/AutoAnnotateApp#179] opened 2022-10-18 14:47 UTC
Not sure if I mentioned this earlier. The default size of the ellipses is too large for my needs. I usually enlarge the nodes and then reduce the ellipse size manually for the final figure. However, each time I move a node, the original size of the ellipse comes back. 
Is it possible to add a slide bar to adjust the size of the ellipse (below the opacity and border width ones?

**Comment by mikekucera** [comment] 2022-10-24 12:56
Duplicate of #134

**Closed as completed by mikekucera** 2022-10-24 12:56 UTC
Labels: enhancement
